### ISSUE TITLE
Toutes les requêtes excepté /login ont changé

### ISSUE THREAD

**Issue by Clemorange22** [a2br/ecoledirecte.js#343]
Dans toutes les requêtes excepté /login, le token d'autorisation doit maintenant être passé dans le header "x-token" au lieu du body de la requête
Toutes les requêtes necéssitant un token sont donc potentiellement obsolètes
EDIT : les anciennes requêtes fonctionnent toujours

**Comment by a2br** [comment]
Merci d'avoir prévenu ! Ça fait longtemps que j'ai pas touché à ED.js, mais je crois que j'avais déjà implémenté ça. En tout cas, on dirait que le module fonctionne toujours.
